import Head from "next/head";
import { Poppins, Roboto } from "@next/font/google";
import Post from "@/components/Post";
import styles from "@/styles/Home.module.css";
import Image from "next/image";

const poppins = Poppins({
  display: "optional",
  weight: ["700", "400"],
  subsets: ["latin"],
});

const roboto = Roboto({
  display: "optional",
  weight: ["700", "400"],
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <nav className={styles.nav}>
          <span className={roboto.className}>
            RocketBlog<i className={styles.dotBlog}>.</i>
          </span>
          <ul className={styles.containerLinks}>
            <li>
              <a className={roboto.className} href="#">
                Home
              </a>
            </li>
            <li>
              <a className={roboto.className} href="#">
                Sobre
              </a>
            </li>
            <li>
              <a className={roboto.className} href="#">
                Artigos
              </a>
            </li>
            <li>
              <a className={roboto.className} href="#">
                Contato
              </a>
            </li>
          </ul>
          <div className={styles.containerSearch}>
            <input placeholder="Search" className={styles.inputSearch} />
            <button type="submit" className={styles.btnSearch}>
              <Image src="/search.svg" alt="" width={24} height={24} />
            </button>
          </div>
        </nav>
        <section className={styles.sectionHeader}>
          <div>
            <Post
              postTitle="Veja o guia definitivo para conquistar seus objetivos como DEV em 2022"
              postDescription="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nibh nibh eu in aliquet ut adipiscing neque. Sed volutpat aenean sit vitae, sed tristique placerat hac. "
            />
            <a href="#" className={roboto.className}>
              Ver Mais{" "}
              <Image src="/arrow-right.svg" alt="" width={24} height={24} />
            </a>
          </div>
          <img
            src="https://images.unsplash.com/photo-1587620962725-abab7fe55159?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1031&q=80"
            alt=""
          />
        </section>
      </header>
      <main className={styles.main}>
        <section className={styles.sectionPosts}>
          <Post
            img="https://images.unsplash.com/photo-1587620962725-abab7fe55159?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1031&q=80"
            date="Janeiro, 04/22"
            postTitle="Começando no ReactJS em 2022"
            postDescription="Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam nostrum
        error a aut sit illo et impedit alias enim asperiores dolore obcaecati,
        dignissimos est id deserunt doloribus fugiat porro exercitationem."
          />
          <div className={styles.containerPostsColunm}>
            <Post
              date="Janeiro, 04/22"
              postTitle="Começando no ReactJS em 2022"
              postDescription="Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam nostrum
      error a aut sit illo et impedit alias enim asperiores dolore obcaecati,
      dignissimos est id deserunt doloribus fugiat porro exercitationem."
            />
            <Post
              date="Janeiro, 04/22"
              postTitle="Começando no ReactJS em 2022"
              postDescription="Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam nostrum
      error a aut sit illo et impedit alias enim asperiores dolore obcaecati,
      dignissimos est id deserunt doloribus fugiat porro exercitationem."
            />
          </div>
        </section>
        <section className={styles.sectionPosts}>
          <Post
            img="https://images.unsplash.com/photo-1587620962725-abab7fe55159?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1031&q=80"
            date="Janeiro, 04/22"
            postTitle="Começando no ReactJS em 2022"
            postDescription="Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam nostrum
      error a aut sit illo et impedit alias enim asperiores dolore obcaecati,
      dignissimos est id deserunt doloribus fugiat porro exercitationem."
          />
          <Post
            img="https://images.unsplash.com/photo-1587620962725-abab7fe55159?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1031&q=80"
            date="Janeiro, 04/22"
            postTitle="Começando no ReactJS em 2022"
            postDescription="Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam nostrum
      error a aut sit illo et impedit alias enim asperiores dolore obcaecati,
      dignissimos est id deserunt doloribus fugiat porro exercitationem."
          />
          <Post
            img="https://images.unsplash.com/photo-1587620962725-abab7fe55159?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1031&q=80"
            date="Janeiro, 04/22"
            postTitle="Começando no ReactJS em 2022"
            postDescription="Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam nostrum
      error a aut sit illo et impedit alias enim asperiores dolore obcaecati,
      dignissimos est id deserunt doloribus fugiat porro exercitationem."
          />
        </section>
      </main>
    </>
  );
}
